- set_fact:
    git_home: "/srv/git"

- name: Create user {{ git_username }}
  user:
    name: "{{ git_username }}"
    shell: /usr/bin/git-shell
    home: "{{ git_home }}"
    group: "{{ ansible_committers_group | default(omit) }}"

- name: Create git-shell-commands directory
  file:
    name: "{{ git_home }}/git-shell-commands"
    state: directory

- name: Copy commands in the git-shell-commands directory
  copy:
    dest: "{{ git_home }}/git-shell-commands/{{ item }}"
    src: "{{ item }}"
    mode: "0755"
  with_items:
  - list
  - help
  - update_external_roles

- name: Copy templated command in the git-shell-commands directory
  template:
    dest: "{{ git_home }}/git-shell-commands/{{ item }}"
    src: "{{ item }}"
    mode: "0755"
  with_items:
  - clean_ssh_public_keys

- name: Link repositories in the home
  file:
    state: link
    dest: "{{ git_home }}/{{ item }}.git"
    src: "{{ git_repositories_dir }}/{{ item }}"
  with_items:
  - public
  - private
