- set_fact: checkout_dir=/usr/local/src/ansible

- name: install ansible deps
  action: "{{ ansible_pkg_mgr }} pkg={{ item }} state=installed"
  with_items:
  - python-jinja2
  - python-paramiko
  - python-httplib2
  - PyYAML
  - python-keyczar

- git: repo=https://github.com/ansible/ansible.git dest={{ checkout_dir }}

- template: dest=/usr/local/bin/{{ item }} src={{ item }} mode=0755
  with_items:
  - ansible_git
  - ansible_git_update

- file: dest=/usr/bin/{{ item }} src=/usr/local/bin/ansible_git state=link
  with_items:
  - ansible
  - ansible-doc
  - ansible-galaxy
  - ansible-playbook
  - ansible-pull
  - ansible-vault

- file: dest=/etc/ansible state=directory

- cron: name="update ansible git" minute=*/20 job=/usr/local/bin/ansible_git_update
