- name: Install ansible from package (classic)
  package:
    name:
    - ansible
    - python3-netaddr
    state: present
  when: ansible_distribution_major_version|int < 35

- name: Install ansible from package
  package:
    name:
    - ansible-base
    - python3-netaddr
    state: present
  when: ansible_distribution_major_version|int >= 35

- name: Install rpm collections
  package:
    name: "ansible-collection-{{ item | replace('.', '-') }}"
    state: present
  with_items: "{{ rpm_collections }}"
