- set_fact: checkout_dir=/usr/local/src/ansible

- name: Install ansible deps from {{ ansible_pkg_mgr }}
  action: "{{ ansible_pkg_mgr }} pkg={{ item }} state=installed"
  with_items:
  - python-jinja2
  - python-paramiko
  - python-httplib2
  - PyYAML
  - python-keyczar

- git: repo=https://github.com/ansible/ansible.git dest={{ checkout_dir }}
  name: Checkout git in {{ checkout_dir }}

- name: Create helper scripts
  template: dest=/usr/local/bin/{{ item }} src={{ item }} mode=0755
  with_items:
  - ansible_git
  - ansible_git_update

- name: Create compatibility links
  file: dest=/usr/bin/{{ item }} src=/usr/local/bin/ansible_git state=link
  with_items:
  - ansible
  - ansible-doc
  - ansible-galaxy
  - ansible-playbook
  - ansible-pull
  - ansible-vault

- name: Create /etc/ansible directory
  file: dest=/etc/ansible state=directory

- name: Set cron to automatically update the checkout
  cron: name="update ansible git" minute=*/20 job=/usr/local/bin/ansible_git_update
