- name: Install ansible from package
  package:
    name:
    - ansible
    - python-netaddr
    state: present

- name: Install rpm collections
  package:
    name: "ansible-collection-{{ item | replace('.', '-') }}"
    state: present
  with_items: "{{ rpm_collections }}"
