---
- name: install ansible
  action: "{{ ansible_pkg_mgr }} pkg={{ item }} state=installed"
  with_items:
  - ansible
  - git

- user: name={{ ansible_username }} generate_ssh_key=yes
  register: ansible_user

- template: dest=/etc/ansible/ansible.cfg src=ansible.cfg mode=0755

- file: path={{ cache_folder }} state=directory owner={{ ansible_username }} mode=0755

- file: path={{ git_repositories_dir }} state=directory

- file: path={{ git_repositories_dir }}/{{ item }} state=directory
  with_items:
  - public
  - private

- shell: creates={{ git_repositories_dir }}/{{ item }}/config chdir={{ git_repositories_dir }}/{{ item }} git init --bare -q --shared=group
  with_items:
  - public
  - private

- copy: dest={{ git_repositories_dir }}/{{ item }}/hooks/post-receive src=post-receive.{{ item }}.sh mode=0755
  with_items:
  - public
  - private

- copy: src={{ item }} dest=/usr/local/bin/{{ item }} mode=0755
  with_items:
  - merge_git.sh
  - ansible_run_all.sh
  - generate_ansible_command.py

- template: src={{ item }} dest=/usr/local/bin/{{ item }} mode=0755
  with_items:
  - file_changed_commit.sh

- cron: name="merge git {{ git_repositories_dir }}" job="/usr/local/bin/merge_git.sh {{ git_repositories_dir }}" minute=*/5

- cron: name="ansible run" user={{ ansible_username }} job=/usr/local/bin/ansible_run_all.sh hour=4
