---
- name: install git
  action: "{{ ansible_pkg_mgr }} pkg={{ item }} state=installed"
  with_items:
  - git

- user: name={{ ansible_username }} generate_ssh_key=yes

- group: name={{ ansible_admin_group }}
  when: ansible_admin_group is defined

- include: install_ansible_rpm.yml
  when: use_ansible_HEAD is not defined

- include: install_ansible_git.yml
  when: use_ansible_HEAD is defined

- template: dest=~{{ ansible_username }}/.ssh/config src=ssh_config

- template: dest=/etc/ansible/ansible.cfg src=ansible.cfg mode=0755

- file: path={{ cache_folder }} state=directory owner={{ ansible_username }} mode=0755

- file: path={{ git_repositories_dir }} state=directory

- file: path={{ git_repositories_dir }}/{{ item }} state=directory group={{ ansible_admin_group | default(omit) }} mode="u=rwx,g=rwxs"
  with_items:
  - public
  - private

- template: dest=/etc/sudoers.d/{{ ansible_admin_group }}_cmd_config src=sudoers_cmd_config validate='visudo -cf %s'
  when: ansible_admin_group is defined

- shell: creates={{ git_repositories_dir }}/{{ item }}/config chdir={{ git_repositories_dir }}/{{ item }} git init --bare -q --shared=group
  with_items:
  - public
  - private

- template: dest={{ git_repositories_dir }}/{{ item }}/hooks/post-receive src=post-receive.{{ item }}.sh mode=0755
  with_items:
  - public
  - private

- copy: src={{ item }} dest=/usr/local/bin/{{ item }} mode=0755
  with_items:
  - checkout_git_repos.sh
  - ansible_run_all.sh
  - generate_ansible_command.py
  - update_galaxy.sh
  - update_ansible_config.sh

- template: src=update_galaxy.sudoers dest=/etc/sudoers.d/update_galaxy validate='visudo -cf %s'

- template: src={{ item }} dest=/usr/local/bin/{{ item }} mode=0755
  with_items:
  - file_changed_commit.sh

- cron: name="merge git {{ git_repositories_dir }}" job="/usr/local/bin/checkout_git_repos.sh {{ git_repositories_dir }}" minute=*/5

- cron:
      name="ansible run"
      user={{ ansible_username }}
      job=/usr/local/bin/ansible_run_all.sh
      minute="{{ ansible_run_minute | default(omit) }}"
      hour="{{ ansible_run_hour | default(omit) }}"

- include: git_shell.yml
  when: use_git_shell is defined
